#ifndef MOCK
#error Please define MOCK before including the list of functions to be mocked
#endif

MOCK(account_t *account_get, bee_t *bee, const char *id)
MOCK(bee_user_t *bee_user_by_handle,bee_t *bee, struct im_connection *ic, const char *handle)
MOCK(bee_user_t *bee_user_new,bee_t *bee, struct im_connection *ic, const char *handle, bee_user_flags_t flags)
MOCK(char *set_eval_account,set_t *set, char *value)
MOCK(char *set_getstr,set_t **head, const char *key)
MOCK(char *sha1_random_uuid,sha1_state_t * context)
#ifndef debug
#define debug(text ...) imcb_log(ic, text);
#endif
MOCK(gboolean root_command_add,const char *command, int params, void (*func)(irc_t *, char **args), int flags)
MOCK(gboolean ssl_sockerr_again,void *ssl)
MOCK(gint b_input_add,gint source, b_input_condition condition, b_event_handler function, gpointer data)
MOCK(gint b_timeout_add,gint timeout, b_event_handler function, gpointer data)
MOCK(int bool2int,char *value)
MOCK(int is_bool,char *value)
MOCK(int set_getbool,set_t **head, const char *key)
MOCK(int set_getint,set_t **head, const char *key)
MOCK(int set_reset,set_t **head, const char *key)
MOCK(int set_setint,set_t **head, const char *key, int value)
MOCK(int set_setstr,set_t **head, const char *key, char *value)
MOCK(int ssl_getfd,void *conn)
MOCK(int ssl_read,void *conn, char *buf, int len)
MOCK(int ssl_write,void *conn, const char *buf, int len)
MOCK(int url_set,url_t *url, const char *set_url)
MOCK(irc_user_t *irc_user_by_name,irc_t *irc, const char *nick)
MOCK(set_t *set_add,set_t **head, const char *key, const char *def, set_eval eval, void *data)
MOCK(set_t *set_find,set_t **head, const char *key)
MOCK(struct bee_user *imcb_buddy_by_handle,struct im_connection *ic, const char *handle)
MOCK(struct groupchat *bee_chat_by_title,bee_t *bee, struct im_connection *ic, const char *title)
MOCK(struct groupchat *imcb_chat_new,struct im_connection *ic, const char *handle)
MOCK(struct http_request *http_dorequest,char *host, int port, int ssl, char *request, http_input_function func, gpointer data)
MOCK(struct im_connection *imcb_new,account_t *acc)
MOCK(void account_off,bee_t *bee, account_t *a)
MOCK(void account_on,bee_t *bee, account_t *a)
MOCK(void b_event_remove,gint id)
MOCK(void http_close,struct http_request *req)
MOCK(void http_decode,char *s)
MOCK(void http_encode,char *s)
MOCK(void imcb_add_buddy,struct im_connection *ic, const char *handle, const char *group)
MOCK(void imcb_ask_auth,struct im_connection *ic, const char *handle, const char *realname)
MOCK(void imcb_ask,struct im_connection *ic, char *msg, void *data, query_callback doit, query_callback dont)
MOCK(void imcb_buddy_msg,struct im_connection *ic, const char *handle, const char *msg, guint32 flags, time_t sent_at)
MOCK(void imcb_buddy_nick_hint,struct im_connection *ic, const char *handle, const char *nick)
MOCK(void imcb_buddy_status,struct im_connection *ic, const char *handle, int flags, const char *state, const char *message)
MOCK(void imcb_buddy_typing,struct im_connection *ic, const char *handle, guint32 flags)
MOCK(void imcb_chat_add_buddy,struct groupchat *c, const char *handle)
MOCK(void imcb_chat_free,struct groupchat *c)
MOCK(void imcb_chat_msg,struct groupchat *c, const char *who, char *msg, guint32 flags, time_t sent_at)
MOCK(void imcb_chat_name_hint,struct groupchat *c, const char *name)
MOCK(void imcb_chat_remove_buddy,struct groupchat *c, const char *handle, const char *reason)
MOCK(void imcb_chat_topic,struct groupchat *c, char *who, char *topic, time_t set_at)
MOCK(void imcb_connected,struct im_connection *ic)
MOCKVA(void imcb_error,struct im_connection *ic, char *format, ...)
MOCKVA(void imcb_log,struct im_connection *ic, char *format, ...)
MOCK(void imcb_remove_buddy,struct im_connection *ic, const char *handle, char *group)
MOCK(void imcb_rename_buddy,struct im_connection *ic, const char *handle, const char *realname)
MOCK(void imc_logout,struct im_connection *ic, int allow_reconnect)
MOCKVA(void irc_rootmsg,irc_t *irc, char *format, ...)
MOCKVA(void log_message,int level, const char *message, ...)
MOCK(void op_log_message,void *opdata, const char *message)
MOCK(void random_bytes,unsigned char *buf, int count)
MOCK(void register_protocol,struct prpl *p)
MOCK(void sha1_append,sha1_state_t *ctx, const guint8 * message_array, guint len)
MOCK(void sha1_init,sha1_state_t *ctx)
MOCK(void *ssl_connect,char *host, int port, gboolean verify, ssl_input_function func, gpointer data)
MOCK(void ssl_disconnect,void *conn_)
